name: Release

on:
  release:
    types: [published]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Run the Cake script
        uses: cake-build/cake-action@v1
        with:
          target: Publish
          packageVersion: $GITHUB_REF
          cake-version: 1.0.0-rc0001