name: Release

on:
  release:
    types: [published]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Run the Cake script
        uses: cake-build/cake-action@v1
        with:
          target: Publish
          packageVersion: $GITHUB_REF